version: '3'

services:
  db:
    image: mariadb:10
    restart: unless-stopped
    environment:
      - MYSQL_USER=${TTRSS_DB_USER}
      - MYSQL_PASSWORD=${TTRSS_DB_PASS}
      - MYSQL_ROOT_PASSWORD=${TTRSS_DB_PASS}
      - MYSQL_DATABASE=${TTRSS_DB_NAME}
    volumes:
      - db:/var/lib/mysql

  app:
    build:
      context:
        ./app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app:/var/www/html
      - ./config.d:/opt/tt-rss/config.d:ro
    depends_on:
      - db

  backups:
    build:
      context:
        ./app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - backups:/backups
      - app:/var/www/html
    depends_on:
      - db
    command: /opt/tt-rss/dcron.sh -f

  updater:
    build:
      context:
        ./app
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - app:/var/www/html
      - ./config.d:/opt/tt-rss/config.d:ro
    depends_on:
      - app
    command: /opt/tt-rss/updater.sh

  web-nginx:
    build: ./web-nginx
    restart: unless-stopped
    ports:
      - ${HTTP_PORT}:80
    volumes:
      - app:/var/www/html:ro
    depends_on:
      - app

volumes:
  db:
  app:
  certs:
  backups:
